version: '3.8'

services:
  tempo-detector:
    build: .
    volumes:
      - ./audio:/app/audio
    environment:
      - DISPLAY=${DISPLAY}
    command: ["python", "tempo_detector.py"]

volumes:
  audio:
